### ISSUE TITLE
When i add a bot

### ISSUE THREAD

**Issue by Dany-LF** [Ankrad/Discord-Bot-List#17]
It is not put in the db of mongodb so that when I restart the project on glitch the list of bots is deleted.

**Comment by Ankrad** [comment]
So unverified bots are in the database, just their state is **unverified** so they won't show up on the site. When you verify them, their state changes to **verified**. Is that the whole error or is there more? Can you please show me the whole error stack trace

**Comment by Dany-LF** [comment]
When i add a bot with the website i don't have any error but the bot isn't put in mongodb

MONGODBURL: mongodb+srv://user:pass@name-7bzzc.gcp.mongodb.net/botlist?retryWrites=true&w=majority

This is the problem you think?

**Comment by Dany-LF** [comment]
And when i add the bot in the server and `verify @bottoverif`

I have again:

```
[2019-12-26 11:01:29] Uncaught Promise Error: 

[2019-12-26 11:01:29] DiscordAPIError: Invalid Form Body

[2019-12-26 11:01:29] roles[2]: The set already contains this value

[2019-12-26 11:01:29]     at RequestHandler.execute (/rbd/pnpm-volume/579667c4-d3e2-41fb-8ff2-f4d101bf37ba/node_modules/.github.com/discordjs/discord.js/5519d6fbaa61abccc27b742f97ad725bf4259265/node_modules/discord.js/src/rest/RequestHandler.js:170:25)

[2019-12-26 11:01:29]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Ankrad** [comment]
> When i add a bot with the website i don't have any error but the bot isn't put in mongodb
> 
> MONGODBURL: mongodb+srv://user:[pass@name-7bzzc.gcp.mongodb.net](mailto:pass@name-7bzzc.gcp.mongodb.net)/botlist?retryWrites=true&w=majority
> 
> This is the problem you think?

try removing the query params (everything after the `?`)

**Comment by ClearlyElevated** [comment]
If you wanna add me to the glitch project I can take a look. But it seems you are doing everything right. Unless you are leaving out some information. 

```(1) Do exactly what u did before to cause the error. 

(2.) copy and paste the entire terminal code & paste it here on [Hastebin](http://www.paste-bin.tk/)

(3.) Paste the link here for me or ankrad to look at```
