### ISSUE TITLE
Not fix bug

### ISSUE THREAD

**Issue by namekinggamerboy** [Ankrad/Discord-Bot-List#27]
![Screenshot_2020-01-26-17-12-18-801](https://user-images.githubusercontent.com/53903319/73134652-14027e80-405f-11ea-8809-518844385893.jpeg)

**Comment by YasmijnVels** [comment]
@namekinggamerboy  send you're error here

**Comment by namekinggamerboy** [comment]
```Logged in as discordbotlist#9611
[2020-01-26 11:40:50] Uncaught Promise Error: 
[2020-01-26 11:40:50] Error: Cannot find module '/app/src/Utils/discordapi'
[2020-01-26 11:40:50] Require stack:
[2020-01-26 11:40:50] - /app/src/Routes/api/bots/submit.js
[2020-01-26 11:40:50] - /app/src/Routes/api/bots.js
[2020-01-26 11:40:50] - /app/src/Routes/api/index.js
[2020-01-26 11:40:50] - /app/src/Routes/index.js
[2020-01-26 11:40:50] - /app/src/Structures/App.js
[2020-01-26 11:40:50] - /app/src/index.js
[2020-01-26 11:40:50]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
[2020-01-26 11:40:50]     at Function.Module._resolveFilename (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/module-alias/2.2.2/node_modules/module-alias/index.js:49:29)
[2020-01-26 11:40:50]     at Function.Module._load (internal/modules/cjs/loader.js:526:27)
[2020-01-26 11:40:50]     at Module.require (internal/modules/cjs/loader.js:666:19)
[2020-01-26 11:40:50]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-01-26 11:40:50]     at Object.<anonymous> (/app/src/Routes/api/bots/submit.js:4:29)
[2020-01-26 11:40:50]     at Module._compile (internal/modules/cjs/loader.js:759:30)
[2020-01-26 11:40:50]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
[2020-01-26 11:40:50]     at Module.load (internal/modules/cjs/loader.js:628:32)
[2020-01-26 11:40:50]     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
[2020-01-26 11:43:37] Uncaught Promise Error: 
[2020-01-26 11:43:37] MongoParseError: URI malformed, cannot be parsed
[2020-01-26 11:43:37]     at parseConnectionString (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/mongodb/3.5.2/node_modules/mongodb/lib/core/uri_parser.js:542:21)
[2020-01-26 11:43:37]     at connect (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/mongodb/3.5.2/node_modules/mongodb/lib/operations/connect.js:297:3)
[2020-01-26 11:43:37]     at ConnectOperation.execute (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/mongodb/3.5.2/node_modules/mongodb/lib/operations/connect.js:208:5)
[2020-01-26 11:43:37]     at executeOperation (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/mongodb/3.5.2/node_modules/mongodb/lib/operations/execute_operation.js:81:17)
[2020-01-26 11:43:37]     at MongoClient.connect (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/mongodb/3.5.2/node_modules/mongodb/lib/mongo_client.js:219:10)
[2020-01-26 11:43:37]     at Function.MongoClient.connect (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/mongodb/3.5.2/node_modules/mongodb/lib/mongo_client.js:389:22)
[2020-01-26 11:43:37]     at module.exports.init (/app/src/Bot/providers/mongodb.js:13:41)
[2020-01-26 11:43:37]     at /rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.github.com/dirigeants/klasa/aee79a51a6e845b6678e96fdd1a7cc1e27fda435/node_modules/klasa/src/lib/structures/base/Store.js:92:62
[2020-01-26 11:43:37]     at /rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/@discordjs/collection/0.1.3/node_modules/@discordjs/collection/dist/index.js:179:20
[2020-01-26 11:43:37]     at Function.from (<anonymous>)```

**Comment by namekinggamerboy** [comment]
@YasmijnVels send your project link only .env not send me ok

**Comment by Ankrad** [comment]
Use the latest version. It is fixed. It's not the filename that was wrong, it was the import: 5a89739

**Comment by YasmijnVels** [comment]
@namekinggamerboy  i don't send me project sorry

**Comment by namekinggamerboy** [comment]
Thx
