### ISSUE TITLE
bot going offline

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#37]
how can i solve this the bot is going offline

```0|index  | Error: connect ETIMEDOUT 162.159.134.234:443
0|index  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
0|index  |   errno: 'ETIMEDOUT',
0|index  |   code: 'ETIMEDOUT',
0|index  |   syscall: 'connect',
0|index  |   address: '162.159.134.234',
0|index  |   port: 443
0|index  | }
PM2      | App [index:0] exited with code [1] via signal [SIGINT]
PM2      | App [index:0] starting in -fork mode-
PM2      | App [index:0] online
0|index  | HTTPError [AbortError]: The user aborted a request.
0|index  |     at RequestHandler.execute (C:\Users\Administrator\Desktop\bots\luna\node_modules\discord.js\src\rest\RequestHandler.js:106:9)
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
0|index  |   name: 'AbortError',
0|index  |   code: 500,
0|index  |   method: 'get',
0|index  |   path: '/gateway/bot'
0|index  | }
0|index  | [2020-02-13 13:30:32] Uncaught Promise Error:
0|index  | [2020-02-13 13:30:32] AbortError: The user aborted a request.
0|index  | [2020-02-13 13:30:32]     at RequestHandler.execute (C:\Users\Administrator\Desktop\bots\luna\node_modules\discord.js\src\rest\RequestHandler.js:106:9)
0|index  | [2020-02-13 13:30:32]     at processTicksAndRejections (internal/process/task_queues.js:93:5)```

**Comment by IamTheRealSami** [comment]
@YasmijnVels Hey there, I think I know the issue. Can you please check if your bot token is right?

**Comment by IamTheRealSami** [comment]
If you have any issues, You can DM me on Discord. `Sami#0067` is my tag.

**Comment by Ankrad** [comment]
Are you getting ratelimited?

**Comment by IamTheRealSami** [comment]
That error isn't for ratelimit. The client was disconnected

**Comment by YasmijnVels** [comment]
@IamTheRealSami @Ankrad 

it's a Cloudflare website bot
![image](https://user-images.githubusercontent.com/59023524/75255844-dec68900-57e2-11ea-8a93-2f45f4e93d19.png)

but how i solve that

**Comment by IamTheRealSami** [comment]
@YasmijnVels Just try resetting your bot token from https://discordapp.com/developers/application 
And copy the token and replace in config. 

If you need any assistance, add me on Discord. My username is ``sannyroyal1#3167``

**Comment by IamTheRealSami** [comment]
And that IP is your nearby region IP from any cloudflare Datacenter proxying the requests.
