### ISSUE TITLE
this.client.guilds.get is not a function

### ISSUE THREAD

**Issue by alekitopi** [Ankrad/Discord-Bot-List#40]
When I start the app, it shows this error:
```
 TypeError: this.client.guilds.get is not a function
[2020-03-18 03:30:48]     at module.exports.init (/root/DiscordBotList/src/Bot/commands/Bots/remove.js:95:37)
[2020-03-18 03:30:48]     at /root/DiscordBotList/node_modules/klasa/src/lib/structures/base/Store.js:92:62
[2020-03-18 03:30:48]     at /root/DiscordBotList/node_modules/@discordjs/collection/dist/index.js:219:20
[2020-03-18 03:30:48]     at Function.from (<anonymous>)
[2020-03-18 03:30:48]     at Map.map (/root/DiscordBotList/node_modules/@discordjs/collection/dist/index.js:217:22)
[2020-03-18 03:30:48]     at Map.init (/root/DiscordBotList/node_modules/klasa/src/lib/structures/base/Store.js:92:27)
[2020-03-18 03:30:48]     at /root/DiscordBotList/node_modules/klasa/src/events/onceReady.js:22:132
[2020-03-18 03:30:48]     at /root/DiscordBotList/node_modules/@discordjs/collection/dist/index.js:219:20
[2020-03-18 03:30:48]     at Function.from (<anonymous>)
[2020-03-18 03:30:48]     at Map.map (/root/DiscordBotList/node_modules/@discordjs/collection/dist/index.js:217:22)
```

And when I try to create a bot is something similar. I think that it's a problem with Discord.JS v12

**Comment by Ankrad** [comment]
Fixed: 58e83a4. Yeah it was a discord.js v12 update (that I don't like at all). They changed the way data is stored so now you need to do `.get()` from the `.cache` of the object.

**Comment by alekitopi** [comment]
Hi, that solves the start error but it still the error when you want to create a bot.
```
2020-03-18 20:28:39] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2020-03-18 20:28:39]   "TypeError: Cannot read property 'member' of undefined\n" +
[2020-03-18 20:28:39]   '    at /root/DiscordBotList/src/Routes/api/bots/submit.js:17:71\n' +
[2020-03-18 20:28:39]   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)')
[2020-03-18 20:28:39]     at KlasaClient.emit (events.js:310:17)
[2020-03-18 20:28:39]     at module.exports.run (/root/DiscordBotList/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-03-18 20:28:39]     at module.exports._run (/root/DiscordBotList/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-18 20:28:39]     at process.emit (events.js:321:20)
[2020-03-18 20:28:39]     at processPromiseRejections (internal/process/promises.js:209:33)
[2020-03-18 20:28:39]     at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

Thanks 😉

**Comment by Ankrad** [comment]
Have you defined `GUILD_ID` in your environment variables correctly?

**Comment by alekitopi** [comment]
Yeah.
