### ISSUE TITLE
MogoDb

### ISSUE THREAD

**Issue by ClearlyElevated** [Ankrad/Discord-Bot-List#5]
Where does the mongo string go? I am willing to reference and add u as an owner to the list free of cost. I dont plan on editing anything. I just mainly want to use it to display my bots on a site.

**Comment by Ankrad** [comment]
In the .env

**Comment by ClearlyElevated** [comment]
thats what i did. Ill show you the error i am getting.if you are willing to help me set it up and get it running. I will def make it worth your time

**Comment by ClearlyElevated** [comment]
i currently have one going right now. https://discordhouse.org but i want to see what this looks like and see if there is things i could use from mine to extend this one or vise versa. i will of course credit you.

**Comment by Ankrad** [comment]
I just pushed a huge update. Try pulling again. The new env file's much clearer

**Comment by ClearlyElevated** [comment]
thank you! will do now

**Comment by ClearlyElevated** [comment]
I got to here.

<img width="1063" alt="Screenshot 2019-08-22 21 09 04" src="https://user-images.githubusercontent.com/51843882/63566232-23662480-c521-11e9-80ad-e10c1b6aa337.png">

**Comment by Ankrad** [comment]
Yeah, you need to add a redirect URI in your developer application page. (added to wiki now: [here](https://github.com/Ankrad/Discord-Bot-List/wiki/Setting-up-your-own-version))

**Comment by ClearlyElevated** [comment]
Did you host it on glitch? im finding two other glitch.me URLS i didnt add?

**Comment by Ankrad** [comment]
Yeah, for testing before uploading it on here. Clearly I didn't remove everything the first time round. I think the only glitch links left are images. If there are others, let me know where. I'll move the images into an assets folder

**Comment by ClearlyElevated** [comment]
im trying to add it to glitch to test it before putting it on a host. but i keep getting errors following the wiki

**Comment by ClearlyElevated** [comment]
thats why i asked

**Comment by Ankrad** [comment]
Are you still getting any errors? If so, send them here.

**Comment by ClearlyElevated** [comment]
I am. But I was able to at least get it running. I'm on mobile so I can't
send then. But it was about a mongo goose par error. As well as join servrr
tab

**Comment by ClearlyElevated** [comment]
Not sure wtf im doing wrong but half of the dependencies I add break the bot. and give it errors. its probably because i dont know how to use glitch vary well. I usually localhost but as far as the website goes idk how to securely bring it online other then with a online provider

**Comment by ClearlyElevated** [comment]
`(node:2694) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
TypeError: Cannot read property 'get' of null
at /app/server.js:101:42
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/body-parser/1.19.0/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
[2019-09-02 14:01:47] Loaded in 2.28s.
[2019-09-02 14:01:48] Successfully initialized. Ready to serve 2 guilds.
.env: line 8: 604471374496530442: command not found
.env: line 40: 414713250832449536: command not found
node v10.15.3, with pnpm
Installing...
Resolving: total 82, reused 52, downloaded 0
Resolving: total 227, reused 198, downloaded 0
 WARN  klasa@0.5.0-dev requires a peer of discord.js@github:discordjs/discord.js#master but version 12.0.0-dev was installed.
 WARN  discord.js: prism-media@1.1.0 requires a peer of ffmpeg-static@^2.4.0 but none was installed.
 WARN  discord.js: prism-media@1.1.0 requires a peer of node-opus@^0.3.1 but none was installed.
 WARN  discord.js: prism-media@1.1.0 requires a peer of opusscript@^0.0.6 but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of @discordjs/uws@^11.149.1 but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of bufferutil@^4.0.1 but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.4 but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of sodium@^3.0.2 but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.4 but none was installed.
 WARN  discord.js@12.0.0-dev requires a peer of zucc@^0.1.0 but none was installed.
Resolving: total 243, reused 243, downloaded 0, done
Total install time: 7197ms
.env: line 8: 604471374496530442: command not found
.env: line 40: 414713250832449536: command not found
🎠🌯 Your app is listening on port 3000
(node:2810) ExperimentalWarning: The fs.promises API is experimental
[2019-09-02 14:02:13] Loaded 28 commands.
[2019-09-02 14:02:13] Loaded 9 inhibitors.
[2019-09-02 14:02:13] Loaded 2 finalizers.
[2019-09-02 14:02:13] Loaded 1 monitors.
[2019-09-02 14:02:13] Loaded 1 languages.
[2019-09-02 14:02:13] Loaded 2 providers.
[2019-09-02 14:02:13] Loaded 24 events.
[2019-09-02 14:02:13] Loaded 2 extendables.
[2019-09-02 14:02:13] Loaded 0 tasks.
[2019-09-02 14:02:13] Loaded 57 arguments.
[2019-09-02 14:02:13] Loaded 10 serializers.
(node:2810) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
TypeError: Cannot read property 'get' of null
at /app/server.js:101:42
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/body-parser/1.19.0/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/f491ba9e-edbd-49ed-a7dd-eb069573da19/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
[2019-09-02 14:02:14] Loaded in 1.88s.
[2019-09-02 14:02:15] Successfully initialized. Ready to serve 2 guilds.`

**Comment by Ankrad** [comment]
That last comment means everything works. You just tried to access the website before the bot fully loaded so it erred.

**Comment by ClearlyElevated** [comment]
yup so far so good. Do i edit the dark theme in main.css? i edited the dark theme to look more like discord. but i dont think i did it right. cuz everyime you login. it loads he white theme for a few seconds then goes to the dark theme.
